# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Lint with pylint
        run: |
          pylint main.py components helper pages
      - name: Check type
        run: |
          mypy --ignore-missing-imports main.py components helper pages
      - name: Test with pytest
        run: |
          pytest

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Lint with pylint
        run: |
          pylint main.py components helper pages
      - name: Check type
        run: |
          mypy --ignore-missing-imports main.py components helper pages
      - name: Test with pytest
        run: |
          pytest

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Lint with pylint
        run: |
          pylint main.py components helper pages
      - name: Check type
        run: |
          mypy --ignore-missing-imports main.py components helper pages
      - name: Test with pytest
        run: |
          pytest
